#!/usr/bin/env node
/* ------------------------------------------------------------------ */
/* scripts/build-sql.mjs — one paste instead of seven.                 */
/*                                                                     */
/* Concatenates supabase/schema.sql and supabase/migrations/*.sql into */
/* a single file in the order they must run, so applying the database  */
/* is one copy-paste into the Supabase SQL editor rather than seven    */
/* trips with a chance to get the order wrong each time.               */
/*                                                                     */
/* The numbered files stay the source of truth — this output is        */
/* generated, never edited, and is gitignored for exactly that reason. */
/*                                                                     */
/* 0005b is Markdown (the two dashboard clicks) and 0007 is the        */
/* verification pass that runs AFTER seeding, so neither is included.  */
/*                                                                     */
/* Usage:                                                              */
/*   node scripts/build-sql.mjs [--out <path>]                         */
/* ------------------------------------------------------------------ */

import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

/** Run order. schema.sql FIRST — 0002/0003 only ALTER what it creates. */
const FILES = [
  'supabase/schema.sql',
  'supabase/migrations/0001_extensions_enums.sql',
  'supabase/migrations/0002_core_tables.sql',
  'supabase/migrations/0003_events_audit_content.sql',
  'supabase/migrations/0004_integrity.sql',
  'supabase/migrations/0005_roles_rls.sql',
  'supabase/migrations/0006_storage.sql',
  'supabase/migrations/0008_availability.sql',
  'supabase/migrations/0009_notifications.sql',
];

const argv = process.argv.slice(2);
const outArg = argv.indexOf('--out');
const OUT = outArg >= 0 ? argv[outArg + 1] : path.join(ROOT, 'supabase', 'APPLY-ALL.generated.sql');

const rule = (s) => `-- ${'='.repeat(74)}\n-- ${s}\n-- ${'='.repeat(74)}\n`;

const parts = [
  rule('Diab Car — full database, in run order. GENERATED by scripts/build-sql.mjs'),
  `-- Do not edit this file. Edit the numbered files in supabase/ and re-run\n`,
  `--   npm run db:sql\n`,
  `--\n`,
  `-- Paste the whole thing into the Supabase SQL editor and run it once.\n`,
  `-- Then: the two dashboard steps in supabase/migrations/0005b_dashboard_steps.md,\n`,
  `-- then \`npm run db:seed\`, then supabase/migrations/0007_verify.sql.\n\n`,
];

let lines = 0;
for (const rel of FILES) {
  const body = await readFile(path.join(ROOT, rel), 'utf8');
  lines += body.split('\n').length;
  parts.push(`\n\n${rule(rel)}\n${body.trimEnd()}\n`);
}

await writeFile(OUT, parts.join(''), 'utf8');

console.log(`\n  Wrote ${path.relative(ROOT, OUT).split(path.sep).join('/')}`);
console.log(`  ${FILES.length} files, ${lines} lines.\n`);
for (const f of FILES) console.log(`    ${f}`);
console.log('\n  Paste it into the SQL editor and run once.\n');
